### ISSUE TITLE
Pojav crash 

### ISSUE THREAD

**Issue by Rirekkuzo** [PojavLauncherTeam/pojavlauncherteam.github.io#157]
Hi recently I tried to play and suddenly this crash come up, any help with this?
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:559)
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:551)
	at com.kdt.mcgui.mcAccountSpinner.lambda$new$2$com-kdt-mcgui-mcAccountSpinner(mcAccountSpinner.java:104)
	at com.kdt.mcgui.mcAccountSpinner$$ExternalSyntheticLambda2.onLoginError(Unknown Source:2)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$1(MicrosoftBackgroundLogin.java:109)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Isokaz** [comment]
Can you send the latest logs?

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
