### ISSUE TITLE
Crash on sign in

### ISSUE THREAD

**Issue by Robro0-625** [PojavLauncherTeam/pojavlauncherteam.github.io#158]
Hello, I was attempting to login and recieved this error:

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:559)
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:551)
	at com.kdt.mcgui.mcAccountSpinner.lambda$new$2$com-kdt-mcgui-mcAccountSpinner(mcAccountSpinner.java:104)
	at com.kdt.mcgui.mcAccountSpinner$$ExternalSyntheticLambda2.onLoginError(Unknown Source:2)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$1(MicrosoftBackgroundLogin.java:109)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:559)
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:551)
	at com.kdt.mcgui.mcAccountSpinner.lambda$new$2$com-kdt-mcgui-mcAccountSpinner(mcAccountSpinner.java:104)
	at com.kdt.mcgui.mcAccountSpinner$$ExternalSyntheticLambda2.onLoginError(Unknown Source:2)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$1(MicrosoftBackgroundLogin.java:109)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

[pjv.zip](https://github.com/user-attachments/files/15754092/pjv.zip)
(contains latestlog and latestcrash)

**Comment by GaucovyAero** [comment]
microsoft currently has some issues with their site, try again or maybe try using the latest pojav github actions build, guide is on the wiki, or maybe also try logging into minecraft.net first and then into pojav
