### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Legacyplayz** [PojavLauncherTeam/pojavlauncherteam.github.io#209]
[20:59:40] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.7
[20:59:41] [ForkJoinPool-1-worker-6/WARN]: Mod inventoryhud uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:59:41] [main/WARN]: Mod resolution failed
[20:59:41] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED clumps 18.0.0.1 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE clumps 18.0.0.1]
[20:59:41] [main/INFO]: Reason: [HARD_DEP clumps 18.0.0.1 {depends minecraft @ [1.21]}, HARD_DEP entityculling 1.6.6 {depends minecraft @ [1.21]}, HARD_DEP fabrishot 1.14.0 {depends minecraft @ [1.21]}, HARD_DEP immediatelyfast 1.2.18+1.21 {depends minecraft @ [1.21]}, HARD_DEP lithium 0.12.7 {depends minecraft @ [1.21]}]
[20:59:41] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.21.1] -> add:minecraft 1.21 ([[1.21,1.21]])]
[20:59:41] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.21.
More details:
	 - Mod 'Clumps' (clumps) 18.0.0.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'EntityCulling' (entityculling) 1.6.6 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Fabrishot' (fabrishot) 1.14.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'ImmediatelyFast' (immediatelyfast) 1.2.18+1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Lithium' (lithium) 0.12.7 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
[20:59:41] [main/WARN]: Failed to open the error gui!
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371) ~[?:?]
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346) ~[?:?]
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open0(FabricMainWindow.java:94) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open(FabricMainWindow.java:88) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.open(FabricGuiEntry.java:51) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:141) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:108) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:86) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:58) ~[?:?]
	at java.desktop/java.awt.Window.initGC(Window.java:493) ~[?:?]
	at java.desktop/java.awt.Window.init(Window.java:512) ~[?:?]
	at java.desktop/java.awt.Window.<init>(Window.java:554) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Frame.java:428) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Frame.java:393) ~[?:?]
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.createUi(FabricMainWindow.java:104) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.lambda$open0$0(FabricMainWindow.java:95) ~[fabric-loader-0.16.7.jar:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]

**Comment by AverageMinecraftuser** [comment]
This is so easy to fix plus this is not a support GitHub

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
